version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "main"
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "release/struts-6-8-x"
    ignore:
      - dependency-name: "org.eclipse.jetty:jetty-maven-plugin"
      - dependency-name: "com.github.ben-manes.caffeine:caffeine"
      - dependency-name: "com.sun.xml.bind:jaxb-impl"
      - dependency-name: "javax.portlet:portlet-api"
      - dependency-name: "javax.servlet:javax.servlet-api"
      - dependency-name: "javax.servlet.jsp:jsp-api"
      - dependency-name: "org.mortbay.jetty:jsp-2.1"
      - dependency-name: "ognl:ognl"
      - dependency-name: "org.hibernate.validator:hibernate-validator"
      - dependency-name: "org.testng:testng"
      - dependency-name: "org.mockito:mockito-core"
      - dependency-name: "opensymphony:sitemesh"
      - dependency-name: "net.sf.jasperreports:jasperreports"
      - dependency-name: "javax.enterprise:cdi-api"
      - dependency-name: "org.springframework:*"
      - dependency-name: "org.apache.struts:struts-annotations"
      - dependency-name: "org.apache.juneau:juneau-marshall"
      - dependency-name: "org.apache.tomcat:tomcat-api"
      - dependency-name: "org.apache.tomcat:tomcat-juli"
      - dependency-name: "org.apache.tomcat:tomcat-jasper"
